apiVersion: v1
kind: Pod
metadata:
  name: build-agent
spec:
  serviceAccountName: jenkins
  containers:
    - name: maven
      image: maven:3.8.1-openjdk-11
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"

    - name: slscan
      image: shiftleft/sast-scan:v2.1.2
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "800m"
          memory: "1Gi"

  restartPolicy: Never
